remove action, use workflow only

diff --git a/.github/workflows/lint-pr-titles.yaml b/.github/workflows/lint-pr-titles.yaml
--- a/.github/workflows/lint-pr-titles.yaml
+++ b/.github/workflows/lint-pr-titles.yaml
@@ -4,32 +4,22 @@ on:
     types: [opened, edited, reopened, synchronize]
 permissions:
   pull-requests: read
-env:
-  YARN_ENABLE_HARDENED_MODE: 0
 jobs:
   pr-title-lint:
     runs-on: ubuntu-latest
     name: Lint PR Title
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          persist-credentials: false
-      - name: Use Node 18
-        uses: actions/setup-node@v4
-        with:
-          node-version: '18'
-          cache: 'yarn'
-          cache-dependency-path: 'yarn.lock'
-      - name: Restore cached node_modules
-        uses: actions/cache@v4
-        id: node_modules
-        with:
-          path: "**/node_modules"
-          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
-      - name: install
-        run: yarn install --immutable
-      - name: Lint PR
-        uses: ./.github/actions/pr-linting
-        with:
-          pr-title: ${{ github.event.pull_request.title }}
+      - name: Check PR Title
+        env: 
+          TITLE: ${{ github.event.pull_request.title}}
+        run: |
+            if [[ "${TITLE,,}" =~ ^\[?\(?wip\]?\)? ]]; then
+            echo "PR is marked as a WIP. Skipping validation."
+            exit 0
+            elif (echo "${TITLE,,}" | grep -P "^(fix|feat|build|chore|docs|test|refactor|ci|localize|bump|revert)(\(([A-Za-z0-9])+\))?:"); then
+            echo "Success"
+            exit 0
+            else
+            echo "PR title validation failed. Please read our PR naming guide on our github wiki to see how to correctly name your PR: https://github.com/adobe/react-spectrum/wiki/Pull-Request-Naming-Guide"
+            exit 1
+            fi
